### ISSUE TITLE
system does not reconnect everything after ACE restart

### ISSUE THREAD

**Issue by slintes** [INAETICS/kubernetes-demo-cluster#11]
When the node where ACE is running is restarted, every agent is restarted as soon as they detect the new ACE instance. But the system does not get into a healthy state, where everything works, there seem to be remote service and/or wiring discovery problems.

**Comment by slintes** [comment]
This still is an issue. A quick look at the viewer showed some exceptions when the felix agent is restarted:

```
gogo: BindException: Address already in use
java.net.BindException: Address already in use
    at java.net.PlainSocketImpl.socketBind(Native Method)
    at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
    at java.net.ServerSocket.bind(ServerSocket.java:375)
    at java.net.ServerSocket.<init>(ServerSocket.java:237)
    at org.apache.felix.gogo.shell.Telnet.start(Telnet.java:118)
    at org.apache.felix.gogo.shell.Telnet.telnetd(Telnet.java:82)
```

```
[CONSOLE] [WARNING] 14:59:59.477 discovery/etcd(481) Could not set etcd watch!
java.lang.NullPointerException
    at org.amdatu.remote.discovery.etcd.EtcdEndpointDiscovery.setDirectoryWatch(EtcdEndpointDiscovery.java:235)
    at org.amdatu.remote.discovery.etcd.EtcdEndpointDiscovery.handleDiscoveryEndpointChange(EtcdEndpointDiscovery.java:201)
```

I looks as if the old java process is still running (telnet port still in use, etcd client is null (cleaned up in stop()) but a new watch should be set)?

Will investigate further...
