### ISSUE TITLE
autoscaler crashes

### ISSUE THREAD

**Issue by slintes** [INAETICS/kubernetes-demo-cluster#15]
```
2015.09.09 15:50:40 INFO - Bundle: org.inaetics.demonstrator.java_impl.coordinator.autoscaler - Got interrupted while polling the queue, going down! - java.lang.InterruptedException: sleep interrupted
    at org.inaetics.demonstrator.coordinator.autoscaler.AutoScalerImpl.lambda$0(AutoScalerImpl.java:144)
    at org.inaetics.demonstrator.coordinator.autoscaler.AutoScalerImpl$$Lambda$10/1732714980.run(Unknown Source)
```

**Comment by slintes** [comment]
and another one:

```
2015.09.09 15:46:45 WARNING - Bundle: org.inaetics.demonstrator.java_impl.coordinator.autoscaler - Unhandled exception while polling the queue! - org.apache.felix.log.LogException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.io.IOException: Connection is closed
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:472)
    at rx.observables.BlockingObservable.last(BlockingObservable.java:229)
    at org.inaetics.demonstrator.coordinator.k8s.KubernetesCoordinatorService.getReplicaCount(KubernetesCoordinatorService.java:142)
    at org.inaetics.demonstrator.coordinator.k8s.KubernetesCoordinatorService.getReplicaCount(KubernetesCoordinatorService.java:66)
    at org.inaetics.demonstrator.coordinator.autoscaler.AutoScalerImpl.scale(AutoScalerImpl.java:125)
    at org.inaetics.demonstrator.coordinator.autoscaler.AutoScalerImpl.checkQueue(AutoScalerImpl.java:99)
    at org.inaetics.demonstrator.coordinator.autoscaler.AutoScalerImpl.lambda$0(AutoScalerImpl.java:146)
    at org.inaetics.demonstrator.coordinator.autoscaler.AutoScalerImpl$$Lambda$10/1732714980.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.felix.log.LogException: java.util.concurrent.ExecutionException: java.io.IOException: Connection is closed
    at org.glassfish.grizzly.impl.SafeFutureImpl$Sync.innerGet(SafeFutureImpl.java:349)
    at org.glassfish.grizzly.impl.SafeFutureImpl.get(SafeFutureImpl.java:255)
    at com.ning.http.client.providers.grizzly.GrizzlyResponseFuture.get(GrizzlyResponseFuture.java:127)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:73)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:42)
    at rx.Observable.subscribe(Observable.java:7621)
    at org.amdatu.kubernetes.rest.HttpClient.invoke(HttpClient.java:171)
    at org.amdatu.kubernetes.rest.HttpClient.getObject(HttpClient.java:107)
    at org.amdatu.kubernetes.rest.KubernetesRestClient.lambda$3(KubernetesRestClient.java:103)
    at org.amdatu.kubernetes.rest.KubernetesRestClient$$Lambda$19/464067888.call(Unknown Source)
    at rx.Observable.unsafeSubscribe(Observable.java:7531)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:215)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:185)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:120)
    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
    at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:106)
    at rx.Subscriber.setProducer(Subscriber.java:177)
    at rx.Subscriber.setProducer(Subscriber.java:171)
    at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:50)
    at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
    at rx.Observable$1.call(Observable.java:144)
    at rx.Observable$1.call(Observable.java:136)
    at rx.Observable$1.call(Observable.java:144)
    at rx.Observable$1.call(Observable.java:136)
    at rx.Observable$1.call(Observable.java:144)
    at rx.Observable$1.call(Observable.java:136)
    at rx.Observable$1.call(Observable.java:144)
    at rx.Observable$1.call(Observable.java:136)
    at rx.Observable$1.call(Observable.java:144)
    at rx.Observable$1.call(Observable.java:136)
    at rx.Observable$1.call(Observable.java:144)
    at rx.Observable$1.call(Observable.java:136)
    at rx.Observable$1.call(Observable.java:144)
    at rx.Observable$1.call(Observable.java:136)
    at rx.Observable.subscribe(Observable.java:7621)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:442)
    ... 12 more
Caused by: org.apache.felix.log.LogException: java.io.IOException: Connection is closed
    at org.glassfish.grizzly.nio.NIOConnection.assertOpen(NIOConnection.java:432)
    at com.ning.http.client.providers.grizzly.HttpTransactionContext$1.onClosed(HttpTransactionContext.java:98)
    at com.ning.http.client.providers.grizzly.HttpTransactionContext$1.onClosed(HttpTransactionContext.java:83)
    at org.glassfish.grizzly.nio.NIOConnection.invokeCloseListener(NIOConnection.java:955)
    at org.glassfish.grizzly.nio.NIOConnection.notifyCloseListeners(NIOConnection.java:828)
    at org.glassfish.grizzly.nio.NIOConnection.terminate0(NIOConnection.java:561)
    at org.glassfish.grizzly.nio.transport.TCPNIOConnection.terminate0(TCPNIOConnection.java:291)
    at org.glassfish.grizzly.nio.NIOConnection$3.completed(NIOConnection.java:524)
    at org.glassfish.grizzly.nio.NIOConnection$3.completed(NIOConnection.java:520)
    at org.glassfish.grizzly.asyncqueue.AsyncWriteQueueRecord.notifyCompleteAndRecycle(AsyncWriteQueueRecord.java:173)
    at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:279)
    at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:169)
    at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:71)
    at org.glassfish.grizzly.AbstractWriter.write(AbstractWriter.java:76)
    at org.glassfish.grizzly.nio.NIOConnection.closeGracefully0(NIOConnection.java:519)
    at org.glassfish.grizzly.nio.NIOConnection.closeWithReason(NIOConnection.java:500)
    at com.ning.http.client.providers.grizzly.GrizzlyAsyncHttpProvider.timeout(GrizzlyAsyncHttpProvider.java:467)
    at com.ning.http.client.providers.grizzly.GrizzlyAsyncHttpProvider$3.onTimeout(GrizzlyAsyncHttpProvider.java:309)
    at org.glassfish.grizzly.utils.IdleTimeoutFilter$DefaultWorker.doWork(IdleTimeoutFilter.java:398)
    at org.glassfish.grizzly.utils.IdleTimeoutFilter$DefaultWorker.doWork(IdleTimeoutFilter.java:377)
    at org.glassfish.grizzly.utils.DelayedExecutor$DelayedRunnable.run(DelayedExecutor.java:158)
    ... 3 more
Caused by: org.apache.felix.log.LogException: java.io.IOException: Timeout exceeded
    ... 8 more
Caused by: java.util.concurrent.TimeoutException: Timeout exceeded
    at com.ning.http.client.providers.grizzly.GrizzlyAsyncHttpProvider.timeout(GrizzlyAsyncHttpProvider.java:462)
    ... 7 more
```

**Comment by slintes** [comment]
for 1: the question is why there is the InterruptedException. One reason could be that the component was stopped. Added some logging to the stop() method in order to find out next time. (INAETICS/demonstrator@321d156e3da4c74f3a1242a75f3d88e2e0681f0e)

for 2: no problem here, there probably just was a temporary problem connecting to the k8s api server. Exception was caught and logged, but the autoscaler continued working.
