### ISSUE TITLE
felix etcd discovery fails after some while

### ISSUE THREAD

**Issue by slintes** [INAETICS/kubernetes-demo-cluster#3]
```
Provisioning service changed:  -> 10.1.82.2:8080
Starting agent...
agent running with provisioning 10.1.82.2:8080
Will update in 60 seconds...
Listening for transport dt_socket at address: 8000
[DEBUG] 04:22:25 (controller) Config initialized: update: true, fixPkg: true, syncDelay: 5, syncInterval: 10, maxRetries: 1
[DEBUG] 04:22:25 (controller) Scheduling controller to run in 5 seconds...
telnetd is running on 0.0.0.0:2019
[DEBUG] 04:22:30 (controller) Controller syncing...
[DEBUG] 04:22:30 (controller) Synchronizing feedback channels: [auditlog]
[DEBUG] 04:22:30 (discovery) Succesfully connected to serverURL: http://10.1.82.2:8080
[DEBUG] 04:22:30 (controller) Feedback send succesfully for channel: auditlog
[DEBUG] 04:22:30 (controller) Checking for agent updates...
[DEBUG] 04:22:30 (discovery) Returning cached serverURL: http://10.1.82.2:8080
[DEBUG] 04:22:30 (controller) No need to install update: no newer agent version available!
[DEBUG] 04:22:30 (controller) Checking for deployment updates...
[DEBUG] 04:22:30 (discovery) Returning cached serverURL: http://10.1.82.2:8080
[DEBUG] 04:22:30 (controller) Need to install update: newer deployment version available!
[INFO] 04:22:30 (controller) Installing streaming deployment update 0.0.0 => 1.0.0
[DEBUG] 04:22:30 (discovery) Returning cached serverURL: http://10.1.82.2:8080
[CONSOLE] [DEBUG  ] 04:22:32.089 topology/promiscuous(71) started (frameworkUUID=ae442499-ae93-4645-85d1-b17963cd8fbb)
[CONSOLE] [DEBUG  ] 04:22:32.100 topology/promiscuous(71) Ignoring Event Endpoint Listener because it is a reference this service instance: {endpoint.listener.scope=(!(endpoint.framework.uuid=ae442499-ae93-4645-85d1-b17963cd8fbb)), objectClass=[org.osgi.service.remoteserviceadmin.RemoteServiceAdminListener, org.osgi.service.remoteserviceadmin.EndpointEventListener, org.osgi.service.remoteserviceadmin.EndpointListener, org.osgi.service.cm.ManagedService], service.id=17, service.pid=org.amdatu.remote.topology.promiscuous
[CONSOLE] [DEBUG  ] 04:22:32.103 topology/promiscuous(71) Ignoring Endpoint Listener because it is a reference this service instance: {endpoint.listener.scope=(!(endpoint.framework.uuid=ae442499-ae93-4645-85d1-b17963cd8fbb)), objectClass=[org.osgi.service.remoteserviceadmin.RemoteServiceAdminListener, org.osgi.service.remoteserviceadmin.EndpointEventListener, org.osgi.service.remoteserviceadmin.EndpointListener, org.osgi.service.cm.ManagedService], service.id=17, service.pid=org.amdatu.remote.topology.promiscuous
[CONSOLE] [DEBUG  ] admin/wiring(118) started (frameworkUUID=ae442499-ae93-4645-85d1-b17963cd8fbb)
[CONSOLE] [DEBUG  ] admin/wiring(118) listener added {endpoint.listener.scope=(!(endpoint.framework.uuid=ae442499-ae93-4645-85d1-b17963cd8fbb)), objectClass=[org.osgi.service.remoteserviceadmin.RemoteServiceAdminListener, org.osgi.service.remoteserviceadmin.EndpointEventListener, org.osgi.service.remoteserviceadmin.EndpointListener, org.osgi.service.cm.ManagedService], service.id=17, service.pid=org.amdatu.remote.topology.promiscuous
[CONSOLE] [INFO   ] 04:22:32.289 topology/promiscuous(71) Adding Remote Service Admin: {objectClass=[org.osgi.service.remoteserviceadmin.RemoteServiceAdmin], remote.configs.supported=[org.inaetics.remote.admin.wiring], remote.intents.supported=[passByValue], service.id=18
[CONSOLE] [INFO   ] 04:22:32.622 topology/promiscuous(71) Configured export filter updated: (service.exported.interfaces=*)
[CONSOLE] [DEBUG  ] 04:22:32.769 discovery/etcd(762) Connecting to http://172.17.8.20:2379
[CONSOLE] [DEBUG  ] 04:22:33.142 discovery/etcd(762) Etcd version is {"etcdserver":"2.1.2","etcdcluster":"2.1.0"}
[CONSOLE] [DEBUG  ] 04:22:33.146 discovery/etcd(762) started (frameworkUUID=ae442499-ae93-4645-85d1-b17963cd8fbb)
[CONSOLE] [DEBUG  ] 04:22:33.155 discovery/etcd(762) Ignoring Endpoint Listener because it is registered as an Endpoint Event Listener as well: {endpoint.listener.scope=(!(endpoint.framework.uuid=ae442499-ae93-4645-85d1-b17963cd8fbb)), objectClass=[org.osgi.service.remoteserviceadmin.RemoteServiceAdminListener, org.osgi.service.remoteserviceadmin.EndpointEventListener, org.osgi.service.remoteserviceadmin.EndpointListener, org.osgi.service.cm.ManagedService], service.id=17, service.pid=org.amdatu.remote.topology.promiscuous
[CONSOLE] [DEBUG  ] 04:22:33.165 discovery/etcd(762) Ignoring Event Endpoint Listener because it is a reference this service instance: {discovery=true, discovery.type=etcd, endpoint.listener.scope=(&(objectClass=*)(endpoint.framework.uuid=ae442499-ae93-4645-85d1-b17963cd8fbb)), objectClass=[org.osgi.service.remoteserviceadmin.EndpointEventListener, org.osgi.service.remoteserviceadmin.EndpointListener], service.id=45
[CONSOLE] [DEBUG  ] 04:22:33.166 discovery/etcd(762) Ignoring Endpoint Listener because it is a reference this service instance: {discovery=true, discovery.type=etcd, endpoint.listener.scope=(&(objectClass=*)(endpoint.framework.uuid=ae442499-ae93-4645-85d1-b17963cd8fbb)), objectClass=[org.osgi.service.remoteserviceadmin.EndpointEventListener, org.osgi.service.remoteserviceadmin.EndpointListener], service.id=45
[CONSOLE] [DEBUG  ] 04:22:33.168 topology/promiscuous(71) Ignoring Endpoint Listener because it is registered as an Endpoint Event Listener as well: {discovery=true, discovery.type=etcd, endpoint.listener.scope=(&(objectClass=*)(endpoint.framework.uuid=ae442499-ae93-4645-85d1-b17963cd8fbb)), objectClass=[org.osgi.service.remoteserviceadmin.EndpointEventListener, org.osgi.service.remoteserviceadmin.EndpointListener], service.id=45
[CONSOLE] [DEBUG  ] 04:22:33.162 discovery/etcd(762) Adding Endpoint Event Listener {endpoint.listener.scope=(!(endpoint.framework.uuid=ae442499-ae93-4645-85d1-b17963cd8fbb)), objectClass=[org.osgi.service.remoteserviceadmin.RemoteServiceAdminListener, org.osgi.service.remoteserviceadmin.EndpointEventListener, org.osgi.service.remoteserviceadmin.EndpointListener, org.osgi.service.cm.ManagedService], service.id=17, service.pid=org.amdatu.remote.topology.promiscuous
[CONSOLE] [DEBUG  ] 04:22:33.285 discovery/etcd(762) registered at etcd index 220010
[CONSOLE] [DEBUG  ] 04:22:33.288 discovery/etcd(762) Initializing peer endpoints at etcd index 220009
[CONSOLE] [DEBUG  ] 04:22:33.288 discovery/etcd(762) Adding /inaetics/discovery/79791cfa-2a40-4fb3-8e3f-b30e55a88820
[CONSOLE] [DEBUG  ] 04:22:33.288 discovery/etcd(762) Adding /inaetics/discovery/42015578-8bcc-4b91-880b-22b60f9768a9
[CONSOLE] [DEBUG  ] 04:22:33.289 discovery/etcd(762) Adding /inaetics/discovery/39ec6374-c1d9-4b79-97ca-5aa76cdecf15
[CONSOLE] [DEBUG  ] 04:22:33.289 discovery/etcd(762) Adding /inaetics/discovery/22cee702-6b34-4844-b698-bf7825e79e8a
[CONSOLE] [DEBUG  ] 04:22:33.289 discovery/etcd(762) Adding /inaetics/discovery/d0d44349-0f68-43e8-bf2c-4aa32e944557
[CONSOLE] [DEBUG  ] 04:22:33.289 discovery/etcd(762) Adding discovery endpoint url: http://10.1.44.2:8080/org.amdatu.remote.discovery.etcd/
[CONSOLE] [DEBUG  ] 04:22:33.291 discovery/etcd(762) Adding discovery endpoint url: http://10.1.12.2:8080/org.amdatu.remote.discovery.etcd/
[CONSOLE] [DEBUG  ] 04:22:33.291 discovery/etcd(762) Adding discovery endpoint url: http://10.1.63.7:8080/org.amdatu.remote.discovery.etcd/
[CONSOLE] [DEBUG  ] 04:22:33.291 discovery/etcd(762) Adding discovery endpoint url: http://10.1.44.229:9999//org.apache.celix.discovery.etcd
[CONSOLE] [DEBUG  ] 04:22:33.291 discovery/etcd(762) Adding discovery endpoint url: http://10.1.12.227:9999//org.apache.celix.discovery.etcd
[CONSOLE] [DEBUG  ] 04:22:33.292 discovery/etcd(762) Setting watch for index 220010
[CONSOLE] [DEBUG  ] 04:22:33.306 discovery/etcd(762) watch was triggered
[CONSOLE] [DEBUG  ] 04:22:33.306 discovery/etcd(762) Handling peer endpoint change at etcd index 220010
[CONSOLE] [DEBUG  ] 04:22:33.306 discovery/etcd(762) Setting watch for index 220011
[CONSOLE] [WARNING] discovery/etcd(223) etcd watch received exception: 400 Bad Request
[CONSOLE] [WARNING] discovery/etcd(223) Could not get node(s)
io.netty.util.concurrent.BlockingOperationException: DefaultPromise@3307ae76(incomplete)
    at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:390)
    at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:283)
    at mousio.client.promises.ResponsePromise.waitForPromiseSuccess(ResponsePromise.java:165)
    at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:41)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery.discoverEndpoints(EtcdNodeDiscovery.java:120)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery.access$5(EtcdNodeDiscovery.java:107)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery$ResponseListener.onResponse(EtcdNodeDiscovery.java:404)
    at mousio.client.promises.ResponsePromise.setException(ResponsePromise.java:124)
    at mousio.client.promises.ResponsePromise.handlePromise(ResponsePromise.java:103)
    at mousio.client.promises.ResponsePromise$1.operationComplete(ResponsePromise.java:47)
    at mousio.client.promises.ResponsePromise$1.operationComplete(ResponsePromise.java:44)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
    at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:415)
    at mousio.etcd4j.transport.EtcdKeyResponseHandler.channelRead0(EtcdKeyResponseHandler.java:95)
    at mousio.etcd4j.transport.EtcdKeyResponseHandler.channelRead0(EtcdKeyResponseHandler.java:18)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:886)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:834)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
[CONSOLE] [WARNING] discovery/etcd(223) etcd watch received exception: 400 Bad Request
[CONSOLE] [WARNING] discovery/etcd(223) Could not get node(s)
io.netty.util.concurrent.BlockingOperationException: DefaultPromise@43bea4a0(incomplete)
    at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:390)
    at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:283)
    at mousio.client.promises.ResponsePromise.waitForPromiseSuccess(ResponsePromise.java:165)
    at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:41)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery.discoverEndpoints(EtcdNodeDiscovery.java:120)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery.access$5(EtcdNodeDiscovery.java:107)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery$ResponseListener.onResponse(EtcdNodeDiscovery.java:404)
    at mousio.client.promises.ResponsePromise.setException(ResponsePromise.java:124)
    at mousio.client.promises.ResponsePromise.handlePromise(ResponsePromise.java:103)
    at mousio.client.promises.ResponsePromise$1.operationComplete(ResponsePromise.java:47)
    at mousio.client.promises.ResponsePromise$1.operationComplete(ResponsePromise.java:44)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
    at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:415)
    at mousio.etcd4j.transport.EtcdKeyResponseHandler.channelRead0(EtcdKeyResponseHandler.java:95)
    at mousio.etcd4j.transport.EtcdKeyResponseHandler.channelRead0(EtcdKeyResponseHandler.java:18)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:886)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:834)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
[CONSOLE] [DEBUG  ] admin/wiring(118) EventAdmin added {objectClass=[org.osgi.service.event.EventAdmin], service.id=49
[CONSOLE] [WARNING] discovery/etcd(223) etcd watch received exception: 400 Bad Request
[CONSOLE] [WARNING] discovery/etcd(223) Could not get node(s)
io.netty.util.concurrent.BlockingOperationException: DefaultPromise@32c0fcb(incomplete)
    at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:390)
    at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:283)
    at mousio.client.promises.ResponsePromise.waitForPromiseSuccess(ResponsePromise.java:165)
    at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:41)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery.discoverEndpoints(EtcdNodeDiscovery.java:120)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery.access$5(EtcdNodeDiscovery.java:107)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery$ResponseListener.onResponse(EtcdNodeDiscovery.java:404)
    at mousio.client.promises.ResponsePromise.setException(ResponsePromise.java:124)
    at mousio.client.promises.ResponsePromise.handlePromise(ResponsePromise.java:103)
    at mousio.client.promises.ResponsePromise$1.operationComplete(ResponsePromise.java:47)
    at mousio.client.promises.ResponsePromise$1.operationComplete(ResponsePromise.java:44)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
    at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:415)
    at mousio.etcd4j.transport.EtcdKeyResponseHandler.channelRead0(EtcdKeyResponseHandler.java:95)
    at mousio.etcd4j.transport.EtcdKeyResponseHandler.channelRead0(EtcdKeyResponseHandler.java:18)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:886)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:834)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
[CONSOLE] [WARNING] discovery/etcd(223) etcd watch received exception: 400 Bad Request
[CONSOLE] [WARNING] discovery/etcd(223) Could not get node(s)
io.netty.util.concurrent.BlockingOperationException: DefaultPromise@1d2b61a5(incomplete)
    at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:390)
    at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:283)
    at mousio.client.promises.ResponsePromise.waitForPromiseSuccess(ResponsePromise.java:165)
    at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:41)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery.discoverEndpoints(EtcdNodeDiscovery.java:120)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery.access$5(EtcdNodeDiscovery.java:107)
    at org.inaetics.wiring.discovery.etcd.EtcdNodeDiscovery$ResponseListener.onResponse(EtcdNodeDiscovery.java:404)
    at mousio.client.promises.ResponsePromise.setException(ResponsePromise.java:124)
    at mousio.client.promises.ResponsePromise.handlePromise(ResponsePromise.java:103)
    at mousio.client.promises.ResponsePromise$1.operationComplete(ResponsePromise.java:47)
    at mousio.client.promises.ResponsePromise$1.operationComplete(ResponsePromise.java:44)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
    at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:415)
    at mousio.etcd4j.transport.EtcdKeyResponseHandler.channelRead0(EtcdKeyResponseHandler.java:95)
    at mousio.etcd4j.transport.EtcdKeyResponseHandler.channelRead0(EtcdKeyResponseHandler.java:18)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:182)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:886)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:834)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by dragontree101** [comment]
hello, do you solve this problem?

**Comment by slintes** [comment]
Hello,

no, we are not working on this issue. I'm not even sure anymore if this has happened more often or only once, we are not actively working on this project at the moment. If you came across this problem in your setup, feel free to create an issue for the Etcd Discovery component of the Amdatu Remote Service project, which is used here:

http://amdatu.org/components/remote.html
https://amdatu.atlassian.net/projects/AMDATURS/issues

Regards, Marc
